### ISSUE TITLE
erase_marked_points sometimes hangs/crashes

### ISSUE THREAD

**Issue by videlec** [flatsurf/flatsurf#263]
```
from flatsurf import EquiangularPolygons, similarity_surfaces
E = EquiangularPolygons((10, 8, 3, 1, 1, 1))
P = E((1, 1, 2, 4), normalized=True)
B = similarity_surfaces.billiard(P, rational=True)
S = B.minimal_cover(cover_type="translation")
S.erase_marked_points()
```
This seems to be a bug in the function `FlatTriangulation::eliminateMaredPoints()` from libflatsurf as one can also replace the last line with
```
from flatsurf.geometry.pyflatsurf_conversion import from_pyflatsurf, to_pyflatsurf
Spy = to_pyflatsurf(S)
Spy.eliminateMarkedPoints()
```

With this other example it even crashes with a segfault
```
sage: from flatsurf import *
sage: E = EquiangularPolygons((10, 7, 2, 2, 2, 1))
sage: P = E((1, 1, 2, 3), normalized=True)
sage: B = similarity_surfaces.billiard(P, rational=True)
sage: S_mp = B.minimal_cover(cover_type="translation")
sage: S = S_mp.erase_marked_points()
```
The traceback is
```
#0  0x00007ffff50813ab in __gmpn_toom22_mul () from /home/vincent/miniconda3/envs/flatsurf/lib/python3.9/site-packages/sage/misc/../../../../libgmp.so.10
flatsurf/sage-flatsurf#1  0x00007ffff50711b4 in __gmpn_mul_n () from /home/vincent/miniconda3/envs/flatsurf/lib/python3.9/site-packages/sage/misc/../../../../libgmp.so.10
flatsurf/sage-flatsurf#2  0x00007ffff506db5a in __gmpn_mul () from /home/vincent/miniconda3/envs/flatsurf/lib/python3.9/site-packages/sage/misc/../../../../libgmp.so.10
flatsurf/sage-flatsurf#3  0x00007ffff5043afe in __gmpz_mul () from /home/vincent/miniconda3/envs/flatsurf/lib/python3.9/site-packages/sage/misc/../../../../libgmp.so.10
flatsurf/sage-flatsurf#4  0x00007ffde0ad7b23 in _nf_elem_mul_red (a=a@entry=0x7fffff7fffa0, b=b@entry=0x7fffff800d30, c=c@entry=0x7fffff8000c0, nf=nf@entry=0x55556003ad40, red=red@entry=1) at mul.c:48
flatsurf/sage-flatsurf#5  0x00007ffde0ad7e52 in nf_elem_mul_red (a=a@entry=0x7fffff800d30, b=b@entry=0x7fffff800d30, c=c@entry=0x7fffff8000c0, nf=nf@entry=0x55556003ad40, red=red@entry=1) at mul.c:184
flatsurf/sage-flatsurf#6  0x00007ffde0ad7f7c in nf_elem_mul (a=a@entry=0x7fffff800d30, b=b@entry=0x7fffff800d30, c=c@entry=0x7fffff8000c0, nf=nf@entry=0x55556003ad40) at mul.c:199
flatsurf/sage-flatsurf#7  0x00007ffde0afc85c in renf_elem_mul (a=0x7fffff800d30, b=0x7fffff800d30, c=0x7fffff8000c0, nf=0x55556003ad40) at renf_elem/mul.c:16
flatsurf/sage-flatsurf#8  0x00007ffde0b1836a in std::function<void (renf_elem_struct*, renf_elem_struct const*, renf_elem_struct const*, renf*)>::operator()(renf_elem_struct*, renf_elem_struct const*, renf_elem_struct const*, renf*) const (__args#3=<optimized out>, __args#2=<optimized out>, __args#1=<optimized out>, __args#0=<optimized out>, this=0x7fffff800160)
    at /opt/conda/conda-bld/e-antic_1612449122203/_build_env/x86_64-conda-linux-gnu/include/c++/9.3.0/bits/std_function.h:688
flatsurf/sage-flatsurf#9  eantic::(anonymous namespace)::binop(eantic::renf_elem_class &, const eantic::renf_elem_class &, const std::function<void(renf_elem_struct*, const renf_elem_struct*, const renf_elem_struct*, renf*)> &) (lhs=..., rhs=..., op=...) at renf_elem_class.cpp:31
flatsurf/sage-flatsurf#10 0x00007ffde0b18971 in eantic::renf_elem_class::operator*= (this=this@entry=0x7fffff800d20, rhs=...) at renf_elem_class.cpp:656
flatsurf/sage-flatsurf#11 0x00007ffde0572b82 in boost::operators_impl::operator* (rhs=..., lhs=...) at /usr/local/src/conda-prefix/include/boost/operators.hpp:259
flatsurf/sage-flatsurf#12 flatsurf::QuadraticPolynomial<eantic::renf_elem_class>::operator< (this=this@entry=0x7fffff801de8, rhs=...) at quadratic_polynomial.cc:101
flatsurf/sage-flatsurf#13 0x00007ffde02768b0 in flatsurf::FlatTriangulation<eantic::renf_elem_class>::operator+ (this=0x555595bef738, shift=...) at flat_triangulation.cc:194
flatsurf/sage-flatsurf#14 0x00007ffde0276f4f in flatsurf::FlatTriangulation<eantic::renf_elem_class>::operator+ (this=<optimized out>, shift=...) at flat_triangulation.cc:230
... (A lot of the same)
#1837 0x00007ffde0276f4f in flatsurf::FlatTriangulation<eantic::renf_elem_class>::operator+ (this=this@entry=0x555560e12078, shift=...) at flat_triangulation.cc:230
#1838 0x00007ffde027942a in flatsurf::FlatTriangulation<eantic::renf_elem_class>::eliminateMarkedPoints (this=0x555560e12078) at flat_triangulation.cc:344
#1839 0x00007ffde027986c in flatsurf::FlatTriangulation<eantic::renf_elem_class>::eliminateMarkedPoints (this=0x555560d04448) at flat_triangulation.cc:370
#1840 0x00007ffde027986c in flatsurf::FlatTriangulation<eantic::renf_elem_class>::eliminateMarkedPoints (this=0x555560be5ff8) at flat_triangulation.cc:370
#1841 0x00007ffde027986c in flatsurf::FlatTriangulation<eantic::renf_elem_class>::eliminateMarkedPoints (this=0x555560abf988) at flat_triangulation.cc:370
#1842 0x00007ffde027986c in flatsurf::FlatTriangulation<eantic::renf_elem_class>::eliminateMarkedPoints (this=0x5555607cf788) at flat_triangulation.cc:370
#1843 0x00007ffde027986c in flatsurf::FlatTriangulation<eantic::renf_elem_class>::eliminateMarkedPoints (this=0x55555f941668) at flat_triangulation.cc:370
#1844 0x00007ffde027986c in flatsurf::FlatTriangulation<eantic::renf_elem_class>::eliminateMarkedPoints (this=0x55555961e940) at flat_triangulation.cc:370
#1845 0x00007ffddd60d02c in ?? ()
#1846 0x0000555558a73830 in ?? ()
#1847 0x00007fffffffa400 in ?? ()
#1848 0x8bf2192fd9117700 in ?? ()
#1849 0x00007ffde2d77730 in WrapperCall(long, unsigned long, void*, void*, void*) ()
   from /home/vincent/miniconda3/envs/flatsurf/lib/python3.9/site-packages/cppyy_backend/lib/libcppyy_backend.so
#1850 0x00007ffde2d786d8 in Cppyy::CallO(long, void*, unsigned long, void*, unsigned long) ()
   from /home/vincent/miniconda3/envs/flatsurf/lib/python3.9/site-packages/cppyy_backend/lib/libcppyy_backend.so
#1851 0x00007ffde0fc524a in CPyCppyy::(anonymous namespace)::InstanceExecutor::Execute(long, void*, CPyCppyy::CallContext*) ()
   from /home/vincent/miniconda3/envs/flatsurf/lib/python3.9/site-packages/libcppyy.cpython-39-x86_64-linux-gnu.so
#1852 0x00007ffde0f945c2 in CPyCppyy::CPPMethod::ExecuteFast(void*, long, CPyCppyy::CallContext*) ()
   from /home/vincent/miniconda3/envs/flatsurf/lib/python3.9/site-packages/libcppyy.cpython-39-x86_64-linux-gnu.so
#1853 0x00007ffde0f94b46 in CPyCppyy::CPPMethod::Execute(void*, long, CPyCppyy::CallContext*) ()
   from /home/vincent/miniconda3/envs/flatsurf/lib/python3.9/site-packages/libcppyy.cpython-39-x86_64-linux-gnu.so
#1854 0x00007ffde0f94c20 in CPyCppyy::CPPMethod::Call(CPyCppyy::CPPInstance*&, _object*, _object*, CPyCppyy::CallContext*) ()
```

**Comment by saraedum** [comment]
Likely the same issue:
```
E = EquiangularPolygons((10, 7, 2, 2, 2, 1))
P = E((1, 1, 2, 3), normalized=True)
B = similarity_surfaces.billiard(P, rational=True)
S_mp = B.minimal_cover(cover_type="translation")
S = S_mp.erase_marked_points()
S, _ = S.normalized_coordinates()
```
