### ISSUE TITLE
make check fails for saddle_connections.py because of missing funcsigs

### ISSUE THREAD

**Issue by videlec** [flatsurf/flatsurf#74]
```
Traceback (most recent call last):
  File "./saddle_connections.py", line 24, in <module>
    import pytest
  File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/pytest.py", line 7, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 12, in <module>
    from _pytest.assertion import rewrite
  File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 23, in <module>
    from _pytest.assertion import util
  File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/_pytest/assertion/util.py", line 10, in <module>
    import _pytest._code
  File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/_pytest/_code/__init__.py", line 6, in <module>
    from .code import Code  # noqa
  File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/_pytest/_code/code.py", line 21, in <module>
    from _pytest.compat import _PY2
  File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/_pytest/compat.py", line 37, in <module>
    from funcsigs import signature, Parameter as Parameter
ImportError: No module named funcsigs
FAIL saddle_connections.py (exit status: 1)
```

**Comment by saraedum** [comment]
That's really odd. `funcsigs` is apparently a Python 2 backport of a Python 3.3 feature. I assume you are not using Python 3.2 here?

**Comment by saraedum** [comment]
I guess you pip installed a recent pytest?

**Comment by videlec** [comment]
not able to reproduce the issue anymore
