### ISSUE TITLE
pyflatsurf tests fail (Sage conversions from sage-flatsurf)

### ISSUE THREAD

**Issue by videlec** [flatsurf/flatsurf#89]
```
====================================================
   flatsurf 0.0.1: test/pyflatsurf/test-suite.log
====================================================

# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: doc.py
============

In file included from input_line_21:1:
/opt/sage/sage-py3-gcc/local/include/e-antic/renfxx.h:308:32: warning: unknown warning group '-Wterminate', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wterminate"
                               ^
In file included from input_line_24:1:
In file included from /opt/sage/sage-py3-gcc/local/include/flatsurf/cppyy.hpp:34:
/opt/sage/sage-py3-gcc/local/include/flatsurf/saddle_connections.hpp:69:32: warning: unknown warning group '-Wnon-template-friend', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wnon-template-friend"
                               ^
**********************************************************************
File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 53, in pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf
Failed example:
    T5 = flatsurf_to_pyflatsurf(S5)
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf[4]>", line 1, in <module>
        T5 = flatsurf_to_pyflatsurf(S5)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 122, in flatsurf_to_pyflatsurf
        check_data(vp, fp, vec)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/utils.py", line 39, in check_data
        raise ValueError("along face {} vectors sum up to {}:\nv_{}={}\nv_{}={}\nv_{}={}".format((i,j,k), v, i, vi, j, vj, k, vk))
    ValueError: along face (1, 2, 3) vectors sum up to (0, 0):
    v_1=((1/2 ~ 0.500000), (1/2*a^3 - 1*a ~ 1.538842))
    v_2=((-1/2*a^2 + 1 ~ -0.809017), (-1/2*a^3 + 3/2*a ~ -0.587785))
    v_3=((1/2*a^2 - 3/2 ~ 0.309017), (-1/2*a ~ -0.951057))
**********************************************************************
File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 56, in pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf
Failed example:
    T7 = flatsurf_to_pyflatsurf(S7)
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf[6]>", line 1, in <module>
        T7 = flatsurf_to_pyflatsurf(S7)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 122, in flatsurf_to_pyflatsurf
        check_data(vp, fp, vec)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/utils.py", line 39, in check_data
        raise ValueError("along face {} vectors sum up to {}:\nv_{}={}\nv_{}={}\nv_{}={}".format((i,j,k), v, i, vi, j, vj, k, vk))
    ValueError: along face (1, 2, 3) vectors sum up to (0, 0):
    v_1=((1/2*a^4 - 2*a^2 + 3/2 ~ -0.400969), (-1/2*a^5 + 5/2*a^3 - 2*a ~ 1.756759))
    v_2=((-1/2*a^2 + 1 ~ -0.222521), (1/2*a^5 - 5/2*a^3 + 5/2*a ~ -0.974928))
    v_3=((-1/2*a^4 + 5/2*a^2 - 5/2 ~ 0.623490), (-1/2*a ~ -0.781831))
**********************************************************************
File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 61, in pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf
Failed example:
    B3 = flatsurf_to_pyflatsurf(A3)
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf[8]>", line 1, in <module>
        B3 = flatsurf_to_pyflatsurf(A3)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 122, in flatsurf_to_pyflatsurf
        check_data(vp, fp, vec)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/utils.py", line 39, in check_data
        raise ValueError("along face {} vectors sum up to {}:\nv_{}={}\nv_{}={}\nv_{}={}".format((i,j,k), v, i, vi, j, vj, k, vk))
    ValueError: along face (1, 2, 3) vectors sum up to (0, 0):
    v_1=((-1/2*alpha^2 ~ -0.147799), (-1/2*alpha^2 + 1/2 ~ 0.352201))
    v_2=((1/2*alpha^2 - 1/2 ~ -0.352201), (alpha-1 ~ -0.456311))
    v_3=((1/2 ~ 0.500000), (1/2*alpha^2 - 1*alpha + 1/2 ~ 0.104110))
**********************************************************************
File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 64, in pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf
Failed example:
    B4 = flatsurf_to_pyflatsurf(A4)
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf[10]>", line 1, in <module>
        B4 = flatsurf_to_pyflatsurf(A4)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 122, in flatsurf_to_pyflatsurf
        check_data(vp, fp, vec)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/utils.py", line 39, in check_data
        raise ValueError("along face {} vectors sum up to {}:\nv_{}={}\nv_{}={}\nv_{}={}".format((i,j,k), v, i, vi, j, vj, k, vk))
    ValueError: along face (1, 2, 3) vectors sum up to (0, 0):
    v_1=((-1/2*alpha^3 - 1/2*alpha^2 ~ -0.204386), (-1/3*alpha^3 - 2/3*alpha^2 + 2/3 ~ 0.440695))
    v_2=((1/2*alpha^3 + 1/2*alpha^2 - 1/2 ~ -0.295614), (alpha-1 ~ -0.481210))
    v_3=((1/2 ~ 0.500000), (1/3*alpha^3 + 2/3*alpha^2 - 1*alpha + 1/3 ~ 0.040515))
**********************************************************************
File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 69, in pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf
Failed example:
    X3 = flatsurf_to_pyflatsurf(W3)
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf[12]>", line 1, in <module>
        X3 = flatsurf_to_pyflatsurf(W3)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 122, in flatsurf_to_pyflatsurf
        check_data(vp, fp, vec)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/utils.py", line 39, in check_data
        raise ValueError("along face {} vectors sum up to {}:\nv_{}={}\nv_{}={}\nv_{}={}".format((i,j,k), v, i, vi, j, vj, k, vk))
    ValueError: along face (1, 2, 3) vectors sum up to (0, 0):
    v_1=(0, (2*a ~ 3.464102))
    v_2=(-1, (-a ~ -1.732051))
    v_3=(1, (-a ~ -1.732051))
**********************************************************************
File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 72, in pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf
Failed example:
    X17 = flatsurf_to_pyflatsurf(W17)
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf[14]>", line 1, in <module>
        X17 = flatsurf_to_pyflatsurf(W17)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py", line 122, in flatsurf_to_pyflatsurf
        check_data(vp, fp, vec)
      File "/home/vincent/programming/flatsurf/flatsurf-library/src/pyflatsurf/pyflatsurf/utils.py", line 39, in check_data
        raise ValueError("along face {} vectors sum up to {}:\nv_{}={}\nv_{}={}\nv_{}={}".format((i,j,k), v, i, vi, j, vj, k, vk))
    ValueError: along face (1, 2, 3) vectors sum up to (0, 0):
    v_1=((a^14 - 15*a^12 + 90*a^10 - 275*a^8 + 450*a^6 - 378*a^4 + 141*a^2 - 17 ~ -3.830891), (-a^15 + 15*a^13 - 90*a^11 + 275*a^9 - 450*a^7 + 378*a^5 - 140*a^3 + 16*a ~ 1.089982))
    v_2=((-a^2 + 2 ~ 1.864944), (a^15 - 15*a^13 + 90*a^11 - 275*a^9 + 450*a^7 - 378*a^5 + 140*a^3 - 15*a ~ -0.722483))
    v_3=((-a^14 + 15*a^12 - 90*a^10 + 275*a^8 - 450*a^6 + 378*a^4 - 140*a^2 + 15 ~ 1.965946), (-a ~ -0.367499))
**********************************************************************
1 items had failures:
   6 of  15 in pyflatsurf.sageflatsurf_pyflatsurf.flatsurf_to_pyflatsurf
***Test Failed*** 6 failures.
FAIL doc.py (exit status: 6)
```

**Comment by videlec** [comment]
I don't understand because if I run the tests in a standalone Sage console it does work...

**Comment by videlec** [comment]
My fault... I wrote code introducing the error (which is not in the git history).
